typescript/vropkg/package.json

Signed-off-by: nvodenicharski99 <nvodenicharski@vmware.com>

add missing dep

---

.github/workflows/build.yml
common/keystore-example/pom.xml
maven/repository/pom.xml

Iac 719 prepare for maven central

---

CHANGELOG.md
docs/versions/latest/Release.md
maven/plugins/bsc/src/main/java/com/vmware/pscoe/maven/plugins/BasicPackageMojo.java

IAC-746 Fix base package behavior when pushing to artifactory

---

.github/workflows/codeql-js.yml
CHANGELOG.md
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/AbstractVrliPackageStore.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/AbxPackageStore.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/CsPackageStore.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/SshPackageStore.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/VcdNgPackageStore.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/VraNgPackageStore.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/VroPackageStore.java
docs/versions/latest/Components/Archetypes/General/Goals/Vrealize Clean.md
docs/versions/latest/Release.md
maven/plugins/vrealize/src/main/java/com/vmware/pscoe/maven/plugins/CleanMojo.java

[IAC-741] vrealize:clean should pass without fail for non-supported archetypes

---

.github/workflows/codeql-java.yml
.github/workflows/codeql-js.yml

Setup codeql

---

CHANGELOG.md
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/AbstractVrliPackageStore.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/VrliPackageStoreV1.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/VrliPackageStoreV2.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/client/vrli/AbstractRestClientVrli.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/client/vrli/RestClientVrliV1.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/client/vrli/RestClientVrliV2.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/store/vrli/VrliPackageStoreTestV1.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/store/vrli/VrliPackageStoreTestV2.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/store/vrops/VropsPackageStoreTest.java
docs/versions/latest/Release.md
maven/base-package/pom.xml
maven/base-package/vrli-package/pom.xml
package-installer/src/main/java/com/vmware/pscoe/iac/installer/Installer.java

…ed configuration option packageImportOverwriteMode is set to true/OVERWRITE
Signed-off-by: akantchev <akantchev@vmware.com>

IAC 733 Add an Option for vRLI Content Pack Overwriting

---

common/artifact-manager/pom.xml

remove snakeyaml explicit usage

---

maven/base-package/actions-package/pom.xml
maven/base-package/base-package/pom.xml
maven/base-package/bsc-package/pom.xml
maven/base-package/cs-package/pom.xml
maven/base-package/pom.xml
maven/base-package/serverless/pom.xml
maven/base-package/typescript-project/pom.xml
maven/base-package/vcd-ng-package/pom.xml
maven/base-package/vra-ng-package/pom.xml
maven/base-package/vra-package/pom.xml
maven/base-package/vrli-package/pom.xml
maven/base-package/vrops-package/pom.xml
maven/base-package/xml-package/pom.xml

move base-package to sub-module

---

.github/workflows/build.yml
.github/workflows/codeql-java.yml
.github/workflows/release.yml
.m2/settings.xml
README.md

update build and release script

---

common/artifact-manager/pom.xml

bump spring-core and json-smart

---

.github/workflows/super-linter.yml

add super-linter

---

.github/linters/.markdown-lint.yml
.github/linters/sun_checks.xml
.markdown-lint.yml
.super-linter.yml
CHANGELOG.md

add md and java rule files

---

common/super-linter/lint-local.sh

add lint local script

---

common/artifact-manager/pom.xml

bump spring-core

---

.github/workflows/build.yml
.github/workflows/codeql-java.yml
.github/workflows/super-linter.yml
CHANGELOG.md
README.md
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/model/vrang/package-info.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/package-info.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/package-info.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/helpers/stubs/package-info.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/store/vrang/package-info.java

update to jdk 17

---

CHANGELOG.md
common/artifact-manager/pom.xml

fix push fatal related to json-smart

---

.github/linters/sun_checks.xml
docs/archive/doc/markdown/use-bundle-installer.md
docs/versions/latest/Release.md
package-installer/src/main/java/com/vmware/pscoe/iac/installer/Installer.java
package-installer/src/main/java/com/vmware/pscoe/iac/installer/package-info.java

[728] Remove the vro_delete_include_dependencies completely - this includes the prompt and the logic behind

---

typescript/npmconv/.gitignore
typescript/npmconv/package-lock.json
typescript/polyglotpkg/.gitignore
typescript/polyglotpkg/package-lock.json
typescript/vro-scripting-api/.gitignore
typescript/vro-scripting-api/package-lock.json
typescript/vropkg/.gitignore
typescript/vropkg/package-lock.json
typescript/vropkg/package.json
typescript/vrotest/.gitignore
typescript/vrotest/package-lock.json
typescript/vrotsc/.gitignore
typescript/vrotsc/package-lock.json

add package-lock.json for exact dep resolvement

---

docs/versions/latest/Release.md

Update Release.md with Upgrade steps for the Custom Forms

---

typescript/npmconv/package-lock.json
typescript/polyglotpkg/package-lock.json
typescript/vro-scripting-api/package-lock.json
typescript/vropkg/package-lock.json
typescript/vrotest/package-lock.json
typescript/vrotsc/package-lock.json

fix package-lock.json repository url

---

.github/workflows/build.yml

Enable 'Import GPG Key' only for main branch

---

vro-types/o11n-plugin-azure/index.d.ts

corrected spelling mistakes in code comments in a file

Fix spelling mistakes on comments code

---

.github/workflows/super-linter.yml
CHANGELOG.md
docs/versions/latest/Release.md
typescript/vro-scripting-api/src/api/ConfigurationElement.ts
typescript/vro-scripting-api/src/configurations.ts
typescript/vro-scripting-api/test/test/Server.test.js

There were issues with the create configuration element that are resolved with these changes. It would return an empty array but now it returns null.
- [] I have added relevant error handling and logging messages to help troubleshooting
Through unit tests.

chore: fix configuration element

---

README.md
SUPPORT.md

Add support statement in the repository

---

.github/linters/sun_checks.xml
CHANGELOG.md
docs/versions/latest/Release.md
maven/plugins/common/src/main/java/com/vmware/pscoe/maven/plugins/AbstractVroPkgMojo.java

Issue 73 is addressed
- [X ] Lint and unit tests pass locally with my changes
- [ X] I have added relevant error handling and logging messages to help troubleshooting
- [ X] I have added tests that prove my fix is effective or that my feature works
- [ X] I have added necessary documentation (if appropriate)
- [X ] I have updated CHANGELOG.md with a short summary of the changes introduced
- [X ] I have tested against live environment, if applicable
- [ X] I have added relevant usage information (As-built)
- [X ] Any structure and/or content vRA-NG improvements are synchronized with vra-ng and ts-vra-ng archetypes
- [X ] Dependencies in pom.xml are up-to-date
- [X ] My changes have been rebased and squashed to the minimal number of relevant commits
- [X ] My changes have a descriptive …

Fix for issue 73.

---

vro-types/pom.xml

Fix build error "You have to use a classifier to attach supplemental artifacts to the project instead of replacing them"

---

CHANGELOG.md
docs/versions/latest/Release.md
maven/plugins/abx/src/main/java/com/vmware/pscoe/maven/plugins/PullMojo.java
maven/plugins/abx/src/main/java/com/vmware/pscoe/maven/plugins/package-info.java
maven/plugins/ssh/src/main/java/com/vmware/pscoe/maven/plugins/SshPullMojo.java
maven/plugins/ssh/src/main/java/com/vmware/pscoe/maven/plugins/package-info.java
maven/plugins/vra-ng/src/main/java/com/vmware/pscoe/maven/plugins/PullMojo.java
maven/plugins/vra-ng/src/main/java/com/vmware/pscoe/maven/plugins/package-info.java
maven/plugins/vra/src/main/java/com/vmware/pscoe/maven/plugins/PullMojo.java
maven/plugins/vra/src/main/java/com/vmware/pscoe/maven/plugins/package-info.java
maven/plugins/vrli/src/main/java/com/vmware/pscoe/maven/plugins/PullMojo.java
maven/plugins/vrli/src/main/java/com/vmware/pscoe/maven/plugins/package-info.java
typescript/npmconv/package-lock.json
typescript/polyglotpkg/package-lock.json
typescript/vro-scripting-api/package-lock.json
typescript/vropkg/package-lock.json
typescript/vrotest/package-lock.json
typescript/vrotsc/package-lock.json

Pull operation was failing on Windows for abx, ssh, vra-ng, vra, vrli.
Whenever a pull was initiated, it was failing with:
pull failed: 'posix:permissions' not supported as initial attribute
when trying to create a temporary directory.
This is due to PosixPermissions which can be used only with POSIX compatible operating systems.
This fix uses another library for temp dir creation which checks if POSIX is supported

Fix for issue 146 - pull not working on windows

---

.github/workflows/build.yml
.github/workflows/codeql-java.yml
.github/workflows/super-linter.yml
typescript/polyglotpkg/test/e2e/node_12/package.json
typescript/polyglotpkg/test/e2e/node_14/package.json
typescript/polyglotpkg/test/e2e/nodejs/package.json

This will fix the build, I believe there was some left over cache from the last deploy, so that was removed. I also force removed the cache, since I saw that the s4u/setup-maven-action was restoring some cache itself.

2.34.1 fix build

---

.github/workflows/build.yml

Add parent project build before all others

---

CHANGELOG.md

Update changelog entry location

---

CHANGELOG.md
docs/versions/latest/Release.md
vro-types/o11n-plugin-aria/.npmignore
vro-types/o11n-plugin-aria/index.d.ts
vro-types/o11n-plugin-aria/package.json
vro-types/o11n-plugin-aria/pom.xml
vro-types/o11n-plugin-ssh/index.d.ts
vro-types/pom.xml

Adding vro types related to the new Aria Automation 8.x vRO plugin 
[vro-types/o11n-plugin-aria] IAC-789 / Adding new Aria Automation Plugin vRO inventory Types

IAC-789 new Aria Auto vRO Plugin  inventory Types

---

CHANGELOG.md
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/VroPackageStore.java
docs/versions/latest/Release.md

Testing was done through a regular import of packages through the installer, with a flag in the 'environment.properties' file: 'vro_enable_backup=true'
Tests were performed on different OS - Windows and macOS. Files are created in their designated folders with correct names.

Iac 799 wrong unix file path separators when creating backup path

---

.github/workflows/stale.yml

Add workflow dispatch event trigger to stale.yml

---

CHANGELOG.md
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientFactory.java
docs/versions/latest/Release.md

Iac 779 install vro package fails with 404 not found in case vro server=vro l 01a is used not fqdn

---

.github/pull_request_template.md

Signed-off-by: Stefan Genov <stefan.genov@broadcom.com>
New PR template, with updated checklist

feat(pr-template): Update the checklist to be more up to date

---

CHANGELOG.md
docs/versions/latest/Release.md

There is a single use case where the vGPU can be attached to the VM as a backing device, which is a `VcVirtualDeviceBackingInfo` class. This property doesn't exist and is not documented in API, but it works in Javascript, Python SDK, and PowerCLI.

Adding support for vgpu in VcVirtualDeviceBackingInfo class

---

CHANGELOG.md
docs/versions/latest/Release.md
typescript/vropkg/src/parse/js.ts

Wider support for types in the @params documentation
> NOTE: The branch is incorrectly set as 264..
#278

278 params

---

.github/workflows/release-drafter.yml

Add testable action for release drafter

---

.github/pull_request_template.md
.github/release-drafter.yml
.github/workflows/stale.yml

Configures new release-drafter and stale bot setting to adhere to new labels

chore: Updated release drafter and PR template

---

CONTRIBUTING.md

Added label details to `CONTRIBUTING.md`

docs: Add label details to CONTRIBUTING.md

---

.github/release-drafter.yml

Added auto labels for whatever matched current labels

chore: Updated with latest `branch` strategies

---

maven/base-package/pom.xml
maven/npmconv/pom.xml
maven/plugins/actions/src/it/basic/pom.xml
maven/plugins/actions/src/it/pull/pom.xml
maven/plugins/polyglot/src/it/basic/pom.xml
maven/plugins/typescript/src/it/basic/pom.xml
maven/plugins/vrealize/src/it/basic/pom.xml
maven/plugins/xml/src/it/pull/pom.xml
maven/polyglot/pom.xml
maven/repository/pom.xml

Bump maven-assembly-plugin and maven-dependency-plugin to 3.7.1
Sorry guys, no testing, just quick PR as a suggestion
[base-package] maven-assembly-plugin and maven-dependency-plugin to 3.7.1
[#368](https://github.com/vmware/build-tools-for-vmware-aria/issues/368)

(#368) Bump maven-assembly-plugin and maven-dependency-plugin to 3.7.1

---

docs/versions/latest/Components/Archetypes/Polyglot/General/Project Structure.md

Add extra documentation as needed in #388. This Closes #388

[docs] (#388) Extend polyglot archetype documentation

---

docs/versions/latest/Release.md
vro-types/o11n-plugin-aria/index.d.ts

https://github.com/vmware/build-tools-for-vmware-aria/issues/347

[vrotsc-types] (#347) Extend Aria plugin types definitions

---

.github/workflows/build.yml

[github] Update upload-artifact action version to 4

---

README.md
maven/base-package/pom.xml
pom.xml

(#405) Bump license-maven-plugin from 2.0.1 to 2.4.0

---

.github/linters/sun_checks.xml
.github/workflows/codeql-java.yml

Reverting temporary changes to sun_checks.yml, codeql-java.yml done for https://github.com/vmware/build-tools-for-vmware-aria/pull/412
Pending build
[](https://github.com/vmware/build-tools-for-vmware-aria/issues/381)

[github] (381) Reverting temporary changes to sun_checks.yml, codeql-java.yml

---

docs/versions/latest/Release.md
vro-types/o11n-plugin-aria/index.d.ts

https://github.com/vmware/build-tools-for-vmware-aria/issues/347

[vrotsc-types] (#347) Add remaining Aria plugin types definitions

---

docs/versions/latest/Release.md
vro-types/o11n-core/index.d.ts

Small fix to the ZipWriter definition
Real live in vRO
Small fix to the ZipWriter definition

[vro-types] Update ZipWriter class interface

---

.github/ISSUE_TEMPLATE/config.yml

Updates the contact link to now point to GitHub discussions instead of Slack.
Closes #323

[area/github] (#323) Update GitHub issue contact link

---

.github/workflows/build.yml
.github/workflows/codeql-java.yml
.github/workflows/codeql-js.yml
.github/workflows/super-linter.yml

Main point of this is to stop the limit or whatever we are hitting due to running many mnay jobs at the same time for **each** commit.
Build:
- Will be triggered on opened PRs as well as forks
- Will be triggered for main, so main will still be build
- Normal Pushes will not trigger as that double builds the project
- If you don't have a PR, you don't get a build
Linter + CodeQL
- Only makes sense during PR

[build] Chore/optimize build for pull request

---

typescript/vropkg/package-lock.json
typescript/vropkg/package.json

Bumps [rollup](https://github.com/rollup/rollup) to 3.29.5 and closes security alert.
Closes https://github.com/vmware/build-tools-for-vmware-aria/security/dependabot/173

build(deps-dev): bump rollup to 3.29.5 in /typescript/vropkg

---

typescript/vro-scripting-api/Gulpfile.ts
typescript/vro-scripting-api/package-lock.json
typescript/vro-scripting-api/package.json

Bumps [rollup](https://github.com/rollup/rollup) to 3.29.5 and closes security alert.
Closes https://github.com/vmware/build-tools-for-vmware-aria/security/dependabot/174

build(deps-dev): bump rollup to 3.29.5 in /typescript/vro-scripting-api

---

.github/workflows/build.yml

Add conditions that explicitly check for Java 17 as our main build target to some of the build tasks which are not required for Java 21 validation (e.g. creating artifacts, uploading to mvn central, etc.).
Excluded the following steps during Java 21 build:
* Set MVN_BUILD_COMMAND for mvn deploy
* Build 'repository'
* Set artifact file name
* Package all artifacts
* Upload artifact

[build] Optimize build process to not bundle Java 21 artifacts

---

docs/versions/latest/Release.md

(docs) Added missing release notes for PR 437

---

docs/versions/latest/Release.md

Update documentation for task  #430 
Update documentation for task  #430 
N/A
Update documentation for task  #430 
Related to issue #430

[documentation] (#430) Updated documentation

---

.github/workflows/build.yml
docs/versions/latest/Release.md

Add the definition of the VcStorageManager class as well as the property in VcServiceContent
Inherits https://github.com/vmware/build-tools-for-vmware-aria/pull/449

[vro-types] Add VcStorageManager class definition

---

docs/versions/latest/Release.md

[vro-types] (#458) Change `011n-plugin-vc` type declarations from interfaces to classes

---

.github/dependabot.yml

Added dependabot configuration for custom labels.
#445

[github] (#445) Add custom dependabot config with proper labelling

---

typescript/npmconv/package-lock.json
typescript/npmconv/package.json
typescript/vrotest/package-lock.json
typescript/vrotest/package.json

Closes security issue: https://github.com/vmware/build-tools-for-vmware-aria/security/dependabot/180

build(deps): Bump `cross-spawn` to `^7.0.6` in /typescript/vrotest/ and typescript/npmconv/

---

.github/trivy.yml
.github/workflows/trivy.yml
docs/versions/latest/Release.md

Trivy will now report scans to GitHub `Security` tab of the repo

[build] (#329) Add Trivy fs scan configuration

---

docs/versions/latest/Release.md
maven/archetypes/polyglot/src/main/resources/archetype-resources/package.json
maven/plugins/abx/src/main/java/com/vmware/pscoe/maven/plugins/PackageMojo.java
package-installer/src/main/java/com/vmware/pscoe/iac/installer/Installer.java

Fix ABX package creating, pushing, installation
Closes #484

[maven,installer] (#484) Unable to package `ABX` project, Add interactive installer option for importing ABX package

---

.github/workflows/release.yml

Update email in release.yml

---

docs/versions/latest/Release.md
typescript/vrotest/src/run.ts

When maven build is executed in Windows, unit tests execution reports error:
Error occurred in unit tests execution: null
The code was changed to execute "npm test" within a shell to ensure execution result is properly returned
Tested with a sample ts project with a unit test.
Tests performed in Windows before and after the fix with the following terminals:
* wsl - no issue observed
* git bash - issue reproduced, fix confirmed
* powershell - issue reproduced, fix confirmed
* cmd - issue reproduced, fix confirmed
#590

[vrotest] (#590) Unit tests execution in Windows reports error

---

docs/versions/latest/Release.md
vro-types/o11n-plugin-activedirectory/index.d.ts

New ad types are added for:
AD_Computer
AD_OrganizationalUnit
AD_UserGroup
Closes #612

[vro-types] (#612) Add new types to `o11n-plugin-activedirectory`

---

typescript/vrotsc/package-lock.json
typescript/vrotsc/package.json

[dependencies] Remove unused `gulp-sourcemaps` dependency

---

README.md
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/model/PackageType.java
docs/versions/latest/Release.md
maven/assembly/src/main/resources/assemblies/iac-assembly.xml
maven/base-package/pom.xml
maven/base-package/vra-ng-package/pom.xml
maven/plugins/common/src/main/java/com/vmware/pscoe/maven/plugins/AbstractIacMojo.java
maven/plugins/vra-ng/src/main/resources/META-INF/plexus/components.xml
maven/plugins/vrealize/src/main/java/com/vmware/pscoe/maven/plugins/ReleaseMojo.java
package-installer/src/main/java/com/vmware/pscoe/iac/installer/Installer.java

[*] Rename `Aria Automation` package files from `.vra-ng` to `vrang`

---

docs/versions/latest/Release.md
vro-types/o11n-plugin-ssh/index.d.ts

…initions and additional methods
Improve type definitions of SSHSession class functions according to the API. Add missing methods. Fix types. Fix descriptions. Fix class attributes.
The return type of some function definitions in the SSHSession class was not correctly defined and few methods were missing.

[vro-types] Improve type definitions of `SSHSession` class members and functions

---

docs/versions/latest/Release.md

Add missing classes to VC plugin

[vro-types] Add missing type definitions to `o11n-plugin-vc`

---

.github/linters/sun_checks.xml
README.md
docs/versions/latest/General/Getting Started/Setting Up Local Environment.md
docs/versions/latest/Release.md
infrastructure/.m2/settings.xml
maven/plugins/actions/src/it/basic/pom.xml
maven/plugins/actions/src/it/pull/pom.xml
maven/plugins/polyglot/src/it/basic/pom.xml
maven/plugins/typescript/src/it/basic/pom.xml
maven/plugins/vrealize/src/it/basic/pom.xml
maven/plugins/xml/src/it/settings.xml

Building BTVA 4.4.0 locally failed due to keystoreVersion 1.0 and 2.0 no longer being present in the maven repository.
Updated the version to the latest available here - 4.4.0:
https://repo.maven.apache.org/maven2/com/vmware/pscoe/build/keystore.example/
Also updated in README and example settings.
Tested by building locally
#685

[maven] (#685) Update `keystore` version references to 4.4.0

---

.github/linters/sun_checks.xml

chore: uncommented sun-checks

---

.github/linters/sun_checks.xml

Restore linter checks purposefully left out in previous PR
Via build
https://github.com/vmware/build-tools-for-vmware-aria/pull/722

[build] Restore commit message linter check

---

maven/archetypes/actions/src/main/resources/archetype-resources/src/test/resources/__packageInPathFormat__/integration-service-1/SampleTests.js
maven/archetypes/mixed/src/main/resources/archetype-resources/actions/src/test/resources/__packageInPathFormat__/integration-service-1/SampleTests.js

Resolves an issue with testing / building a brand new project created from the affected archetypes.
Create a new project from any of the affected archetypes and run the build / test process. It should complete successfully.
- [maven/archetypes] [762](https://github.com/vmware/build-tools-for-vmware-aria/issues/762) Fixed paths to actions in example tests in "mixed" and "actions" archetypes.

[maven/archetypes] (#762) Proper paths to actions used in archetypes.

---

.github/workflows/build.yml
README.md
pom.xml

[maven,github] Simplify build

---

pom.xml

Increase deployment timeout to 6h

---

pom.xml

[maven] Add distribution management tag

---

common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/orchestrator/rest/RestClientVro.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientFactory.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/vcd/rest/RestClientVcdBasicAuthInterceptor.java
docs/versions/latest/Release.md

[artifact-manager] Fix issue where organization name is mandatory even for embedded Orchestrator code push

---

common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/strategy/StrategyForceLatestVersions.java
docs/versions/latest/Components/Archetypes/typescript/General/Getting Started.md
docs/versions/latest/Release.md

[documentation,artifact-manager] (#781) Update documentation and logs regarding import strategies

---

CONTRIBUTING.md
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/operations/models/SymptomDefinitionDTO.java
docs/versions/v4.11.0/Release.md

…ymptomDefinitionDTO + doc update
#864

[artifact-manager] (#864) Fix push of Operations Symptom Definition which compares 2 metrics with numeric values
