vmware/build-tools-for-vmware-aria

CHANGELOG.md
docs/versions/latest/Release.md
typescript/vrotest/package.json
typescript/vrotest/src/build.ts

Helper files are meant to contain fixture or other helper methods and they are not supposed to be part of the code coverage report.
Locally
Helper files are meant to contain fixture or other helper methods and they are not supposed to be part of the code coverage report.
The `.nycrc` configuration that controls the code coverage did not contain an exclude for the helpers
`"**/*.helper.[tj]s"` was added to the configuration to facilitate exclusion of helpers
* None

[IAC-742] Fixed helper files exclusion

---

CHANGELOG.md
docs/versions/latest/Release.md
typescript/vrotsc/e2e/expect/export-helpers/types/actions/index.d.ts
typescript/vrotsc/e2e/expect/export-helpers/types/actions/test.helper.d.ts
typescript/vrotsc/src/compiler/transformers/declaration.ts

Currently the *.helper.ts files are being transpiled, and definitions are being generated. This shouldn't be happening, as there is no reason to have helper files as part of the definitions, since they are test related only.
Tested with a typescript project check attached pic
The helper.ts are now being correctly filtered out by vrtosc, by excluding files that end with: `.helper.ts`.
https://jira.pscoe.vmware.com/browse/IAC-755

[IAC-755] Removed helper.d.ts generation

---

common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/VropsPackageStore.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/cli/CliManagerVrops.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVrops.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/model/vrops/AuthUserDTO.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/model/vrops/AuthUsersDTO.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/PackageMocked.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/store/vrops/VropsPackageStoreTest.java
docs/versions/latest/Release.md
maven/plugins/vrops/src/main/java/com/vmware/pscoe/maven/plugins/PackageMojo.java

If there is a metadata file for activating / deactivating of vROPs dashboards it will be used for activation / deactivation of the imported dashboards for certain users / groups.
Tested using vROPs 8.8 / 8.10 using user / groups activation metadata files created in the dashboards/metadata directory that describe which dashboards for which groups / users will be activated (metadata/dashboardUserActivationMetadata.vrops.json and metadata/dashboardGroupActivationMetadata.vrops.json)

[Task IAC-761] Activate / Deactivate vROPs Dashboards for Users / Groups

---

CHANGELOG.md
docs/versions/latest/Release.md
maven/plugins/common/src/main/java/com/vmware/pscoe/maven/plugins/AbstractInstallNodeDepsMojo.java

Enabled error throwing in case of node dependency installation

[87] Fixed

---

CHANGELOG.md
docs/versions/latest/Release.md
typescript/vro-scripting-api/package.json
typescript/vropkg/package.json
typescript/vrotest/package.json
typescript/vrotsc/package.json

Building the project was not successful due to changed dependency (terser in the vropkg devDependencies).
Updating the typescript folder's package.json files by adding "source-map": "^0.8.0-beta.0" solves the issue.
Running 'mvn install -DskipTests' in the main folder - builds the project successfully.

IAC 777 build failing missing source map

---

CHANGELOG.md
docs/versions/latest/Release.md

Fixed issue for use of “vgpu”
declared type VcVirtualPCIPassthroughBackingInfo used in class VcVirtualPCIPassthrough
Issue Typescript: VcVirtualPCIPassthrough backing doesn’t support VcVirtualPCIPassthroughVmiopBackingInfo #111

111 typescript vcvirtualpcipassthrough backing doesnt support vcvirtualpcipassthroughvmiopbackinginfo

---

CHANGELOG.md
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/PackageStoreFactory.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVrops.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/client/vrli/RestClientVrliV1.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/client/vrli/RestClientVrliV2.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/client/vrli/package-info.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/model/vrli/v1/package-info.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/model/vrli/v2/package-info.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/model/vrops/ResourcesDTO.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/model/vrops/package-info.java
docs/versions/latest/Release.md

Signed-off-by: Alexander Kantchev <akantchev@vmware.com>
Add support for pagination when searching for vROPs resources when pushing vROPs enabled vRLI alerts on large scale environment, thus making possible to find the correct resource name from the target vROPs server during rewriting the vROPs integration data on the vRLI alert. This applies for vRLI alert v1 and v2 API support.
Pushing vROPs enabled vRLI alerts on large scale environments can be done via maven command on a vRLI project:
mvn clean package vrealize:push -P <ENV_NAME>
When pushing vROPs enabled vRLI alerts on large scale environments with more than 100000 the target vROPs integration data could not be found due to page limits in the vROPs resources (fetched only the first 10000 resources on the vROPs level).
When pushing …

[Task IAC-780] Added Pagination Support for fetching vROPs Resources when Pushing vROPs enabled vRLI Alerts

---

CHANGELOG.md
docs/versions/latest/Release.md
typescript/vrotsc/src/compiler/transformers/scripts/saga.ts

Fixing issue The compiled SAGA workflow crashes when no imports are defined in saga yaml #163
1. Create typescript project with SAGA workflow (workflowName.saga.yaml)
2. Leave imports section empty
3. Build the typescript project with maven and push it to vRO environment.
4. Run the compiled saga workflow on vRO environment
Fixed the compiled SAGA workflow crashes when no imports are defined in saga yaml
N/A

[163] Fix typescript saga workflow imports

---

CHANGELOG.md
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVcd.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVcdBasicAuthInterceptor.java
docs/versions/latest/Release.md

When using vCD 10.5 there is a breaking change affecting the way authentication works. This PR introduces a quick fix to the problem.
Tested agains vCD 10.5 and 10.4
Introduced a simple if logic which switches to API version 37.0 if it detects present API version is 38.0 or above

Using api version 37 if 38 or above is detected

---

common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/model/vrang/VraNgCatalogItem.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVraNgPrimitive.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/filters/CustomFolderFileFilter.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/filters/package-info.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgCatalogItemStore.java
docs/versions/latest/Release.md

Fixed problem with pushing vRA content-items to vRA 8.13.x, made content-items in the content.yaml to be no longer case sensitive againist the files in the content-items directory.
Signed-off-by: Alexander Kantchev <akantchev@vmware.com>
Fixed problem with pushing vRA content-items to vRA 8.13.x, made content-items in the content.yaml to be no longer case sensitive againist the files in the content-items directory.
Change the casing of the content-items in the content.yaml (to be different from the file names casing) and try to push the content to vRA environment.
When pushing the vRA content items to  vRA 8.13.x it no longer fails. The content naming in the content.yaml is no longer case sensitive

[Task IAC-785] Fixed problem with pushing vRA content-items to vRA 8.13.x

---

CHANGELOG.md
common/artifact-manager/pom.xml
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/VropsPackageStore.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/model/vrops/VropsPackageDescriptor.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/model/vrops/VropsPackageMemberType.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/model/vrops/package-info.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVrops.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/model/vrops/PolicyDTO.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/PackageMocked.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/package-info.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/store/vrops/VropsPackageStoreTest.java
docs/versions/latest/Release.md
maven/archetypes/vrops/src/main/resources/archetype-resources/content.yaml
maven/base-package/pom.xml
maven/plugins/vrops/src/main/java/com/vmware/pscoe/maven/plugins/PackageMojo.java
maven/plugins/vrops/src/main/java/com/vmware/pscoe/maven/plugins/package-info.java

[Task IAC-786] Implementation of the vROPs default policy feature for vROPs 8.12.x.
Added option for setting default policy for vROPs version 8.12.x by setting it in the default-policy configuration item in the content.yaml file.
On a vROPs project add the following line to the content.yaml file
default-policy:
- Policy Name
After pushing the package to vROPs 8.12.x the default policy should be set to 'Policy Name'. 
Added support for setting default policy in the content.yaml file in the following format:
default-policy:
- Policy Name

[Task IAC-786] Implementation of the vROPs default policy feature for vROPs 8.12.x

---

CHANGELOG.md
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVrops.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/model/vrops/PolicyCustomGroupAssignmentDTO.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/model/vrops/PolicyDTO.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/store/vrops/VropsPackageStoreTest.java
docs/versions/latest/Release.md

[Task IAC-790] Update usage of deprecated vROPs policy (since vROPs 8.12.X)
When pushing vROPs policies on vROPs 8.12.X and later make sure that public API is invoked only (as the older internal API gets deprecated), any internal API calls should be removed, when pushing vROPs policies for older versions of vROPs (prior 8.12.0) make sure that internal API is used only (for backward compatibility).
Tested by pushing vROPs package that contains policies using vROPs version version 8.12.0 and 8.10 (for backward compatibility) .
Update Deprecated Policy APIs for vROPs 8.12.x.

[Task IAC-790] Update usage of deprecated vROPs policy (since vROPs 8.12.X)

---

CHANGELOG.md
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVraNg.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVraNgPrimitive.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgCatalogItemStore.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgCatalogItemStore812.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgCatalogItemStoreTest.java
docs/versions/latest/Release.md

Fix Problem with enabling of vRA blueprint of type workflow for vRA prior 8.12.x
Signed-off-by: Alexander Kantchev <akantchev@vmware.com>
Fixed problem with enabling of vRA blueprints of type 'com.vmw.vro.workflow' during push of such blueprints on vRA prior 8.12.x
Tested with pushing of vRA blueprints of type  'com.vmw.vro.workflow' on vRA 8.10.1 and 8.13.0. On both environments pushing works fine and vRA blueprints get enabled.
When pushing vRA custom forms to vRA version 8.11.2 they are not get enabled by default, thus not visible in the blueprint section.
When pushing vRA custom forms to vRA version 8.11.2 they are get enabled by default and visible in the blueprint section.
If the vRA returns an empty versions array when fetching of latest vRA blueprint version would throw a null …

[Task IAC-788] Fix Problem with enabling of vRA blueprint of type workflow for vRA prior 8.12.x

---

CHANGELOG.md
docs/versions/latest/Release.md
vro-types/o11n-plugin-ssh/index.d.ts

In the existing vRO API SSHSession exitCode has type number. In o11n-plugin-ssh it has type void.
<!--

Fix SSH Session exitCode type

---

CHANGELOG.md
maven/archetypes/ts-vra-ng/src/main/resources/archetype-resources/vra/content.yaml
maven/archetypes/vra-ng/src/main/resources/archetype-resources/content.yaml

IAC-797 Improved default content.yaml archetypes for vRA

---

CHANGELOG.md
docs/versions/latest/Release.md
vro-types/o11n-plugin-sql/index.d.ts

SQLDatabaseManager.getDatabase() function is removed in vRA 7.6 / Aria Automation 8 and above. The function uses name as parameter to retrieve a database. Use getDatabaseById() or getDatabases() and filter by name instead.
* [vro-types/o11n-plugin-aria] IAC-798 / Deprecating SQLDatabaseManager getDatabase() function
Internal ticket: https://jira.pscoe.vmware.com/browse/IAC-798
Fixes #172

IAC-798 Deprecate SQLDatabaseManager getDatabase function

---

CHANGELOG.md
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/VroPackageStore.java
docs/versions/latest/Release.md

Testing was done through a regular import of packages through the installer, with a flag in the 'environment.properties' file: 'vro_enable_backup=true'
Tests were performed by having a different set of packages and versions in the local VMware Aria Orchestrator instance, in order to validate that the highest available version per package name is backed up (in the 'vro' folder), or that if no versions are found for the package in vRO to back up, a message is logged that the back up for this package is skipped.

Iac 778 backup on clean environment throws exception

---

CHANGELOG.md
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVcdBasicAuthInterceptor.java
docs/versions/latest/Release.md

VMware Cloud Director 10.5 and later do not support the /api/sessions API login endpoint.
The /api/sessions API login endpoint is deprecated since VMware Cloud Director API version 33.0. For version 38.0 and later, the /api/sessions API login endpoint is no longer supported. You can use the VMware Cloud Director OpenAPI login endpoints to access VMware Cloud Director.
Service provider access to the system organization- POST cloudapi/1.0.0/sessions/provider
Tenant access to all other organizations apart from the system organization- POST cloudapi/1.0.0/sessions
As per the backward compatibility commitment of VMware Cloud Director, versions 37.2 and earlier continue to support the /api/sessions API login endpoint.
Fixed #166

fix vrealize:push fails for vCD 10.5, API version 38.0

---

CHANGELOG.md
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgSubscriptionStore.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/helpers/filesystem/SubscriptionFsMocks.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/helpers/stubs/SubscriptionMockBuilder.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgSubscriptionStoreTest.java
docs/versions/latest/Release.md

IAC-643 Support subscription with ABX action - point to proper ABX action
1. Create new subscription with execution element vRA ABX action from UI.
2. Export subscription to the package.
3. Delete subscription from  UI.
4. Import package with subscription.
vRA supports subscriptions with execution element vRO Workflow or vRA ABX action. Both are marked as runnable ID when exported and their difference is runnable type. While we can define workflow ID for workflows, we can't do such for ABX actions, which causes issues when importing Subscriptions to different environments (as ABX actions does not have ABX action ID as editable property on POST request).

 IAC-643 Support subscription with ABX action - point to proper ABX action

---

CHANGELOG.md
docs/versions/latest/Release.md
vro-types/o11n-plugin-ssh/index.d.ts

In the existing vRO API SSHSession 'output' has type string. In o11n-plugin-ssh it has type void.

Fix SSH Session 'output' type

---

CHANGELOG.md
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientFactory.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVro.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/auth/VraSsoAuth.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/auth/package-info.java

Tested on a real environment. Currently build tools for VMware Aria does not support setting values on configuration elements which are of type Composite. So for example this is not supported:
```
@Configuration({
name: "Microsoft-PowerShell",
path: "PS CoE/Library/DNS",
attributes:{
msDnsPowershellHost: {
type: "Array/CompositeType(dnsZone:string,dnsServer:PowerShell:PowerShellHost):MsDnsPowershellHost",
value: [],
description: "Allows you to define and use the DNS Servers per Zone/Domain dyrectly. The Powershell host must point to the DNS server itself and must use user with sufficient privileges to create DNS Entries. This is an alternative confifuration to msWindowsJumpVm."
}
}
})
```
so the generated package fails to push. And the REST response reports NullPointerException (on the …

Additional Information on Exception messages when REST API Call fails.

---

CHANGELOG.md
docs/versions/latest/Release.md
vro-types/o11n-plugin-ssh/index.d.ts

In the existing vRO API SSHSession, 'error' and 'status' have type string. In o11n-plugin-ssh it has type void.

Fix SSH Session 'error' and 'status' types

---

CHANGELOG.md
docs/versions/latest/Release.md
typescript/vropkg/src/parse/flat.ts
typescript/vropkg/src/parse/util.ts
typescript/vropkg/src/serialize/tree.ts

Fix issue #165.  Resolved the build error that occurs when executing the 'vro:pull' command on the legacy workflow archetype due to special characters(&) in the workflow path. 
Pull process will be failed with descriptive error message for legacy archetype projects which contains special characters ('&') in workflow paths.
Fix 165 / vro:pull command for legacy archetype fails when workflow folder path name contains character '&'.
https://github.com/vmware/build-tools-for-vmware-aria/issues/165

Fix #165, handle unsupported characters in legacy archetype workflow path

---

CHANGELOG.md
docs/versions/latest/Release.md
vro-types/o11n-plugin-ssh/index.d.ts

In the existing vRO API SSHSession, `cmd`, `pty`, `terminal` have type string. In o11n-plugin-ssh it has type void.

Fix SSH Session 'cmd', 'pty', 'terminal' types

---

CHANGELOG.md
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/cs/CsPipelineStore.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/cs/package-info.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/store/cs/CsPipelineStoreTest.java
docs/versions/latest/Release.md

[IACCOE-809] When importing Aria Pipelines definitions with dependencies to another Pipeline for a rollback the current import mechanism could break because of not importing the dependency pipelines first. This is fixed with this PR by adding a topological sort algorithm to the pipeline YAML files before import.
It was tested in a real environment.

Fixed an issue with CS Pipeline imports

---

common/artifact-manager/pom.xml

Update the Mockito Version to Support JDK 22
Update the Mockito library to be compatible with the latest Java version 22
Run the test cases in the commons/artifact-manager
Update the Mockito library to be compatible with the latest Java version 22

Update the Mockito Version to Support JDK 22

---

CHANGELOG.md
docs/versions/latest/Release.md
packages/ecmascript/src/Shims.ts
typescript/vrotsc/src/compiler/transformer/codeTransformers/shims.ts

Implement Object.setPrototypeOf() method
#264

Implement setProrotypeOf function

---

CHANGELOG.md
docs/versions/latest/Release.md

Convert VcKeyAnyValue from interface to class

---

common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgBlueprintStore.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/helpers/filesystem/BlueprintFsMocks.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgBlueprintStoreTest.java
docs/versions/latest/Release.md

Cloud Template folder name and details.json->name mismatch issue fixed.
_Previous Behavior_ 
- When Cloud-Template folder name and details.json->name mismatch,  folder name is used for validating if the record exists on the server and details.json->name is used for creating/updating the cloud template on server.
_Current Behavior_
- When Cloud-Template folder name and details.json->name mismatch, now an error throwing explaining the mismatch.  
- details.json->name is now used for both validating and creating/updating cloud template on the server.
1.) Create vra 8 project using build-tools-for-vmware-aria.
2.) Create blueprint folder(Test-Blueprint-1) and content.yaml, details.json files accordingly.
3.) Add the blueprint folder name(Test-Blueprint-1) in project content.yaml.
4.) Change …

[artifact-manager] [archetypes/vra] (#210) Cloud Template folder name and the name from details.json mismatch issue fixed in vRA

---

docs/versions/latest/Release.md
typescript/polyglotpkg/package-lock.json
typescript/polyglotpkg/package.json

The issue was that the `polyglotpkg` package had `types/node` set as a devDependency, which, under normal circumstances, would be fine, however, `xmlbuilder2`, one of our dependencies, has a dependency on `@types/node` set to "*". This caused the `xmlbuilder2` package to install the latest version of `@types/node`, which is incompatible with the version of `node` that we are using. We are using version 2.4.1 of `xmlbuilder2`, newest version `3.1.1` does not have this problem.
For more information here are the relevant `package-lock.json` entries:
```json
"node_modules/xmlbuilder2": {
"version": "2.4.1",
"resolved": "https://registry.npmjs.org/xmlbuilder2/-/xmlbuilder2-2.4.1.tgz",
"integrity": "sha512-vliUplZsk5vJnhxXN/mRcij/AE24NObTUm/Zo4vkLusgayO6s3Et5zLEA14XZnY1c3hX5o1ToR0m0BJOPy0UvQ==", …
```

[polyglotpkg] (#259) Packages can now be built correctly

---

packages/ecmascript/src/Map.ts
packages/ecmascript/src/Set.ts

Fix problem with Size in a Map Object when Setting a Value in it
The size property should increase when adding key / values to a map object.
1. Push the ecmascript package to a live environment.
2. Create a dummy workflow with one scrip table task that has the following code in it:
```ts
var __global = System.getContext() || (function () { return this; }).call(null);
var VROES = __global.__VROES || (__global.__VROES = System.getModule("com.vmware.pscoe.library.ecmascript").VROES()), exports = {};
var Map = VROES.Map;
var myMap = new Map();
myMap.set(1,2);
System.log('myMap Size: '.concat(myMap.size));
```
3. Execute the workflow
4. The size printed should be `1`
The size property should increase when adding key / values to a map object.
Issue #353

[ecmascript] (#353) Fix problem with Size in a Map Object when Setting a Value in it

---

docs/versions/latest/Release.md
typescript/vropkg/src/parse/transformers.ts
typescript/vropkg/src/parse/util.ts

`for each` is valid syntax in the Java's Rhino engine, but not in normal JS.
When pulling a workflow with `for each` statements, the action would be pulled, but then would not be able to be pushed as the syntax is invalid.
`for each` statements are now being converted to `for` statements when pulling a workflow.
Example:
```js
var test = ["ya", "da"]
for each (var i in test) {
for each (var y in test) {
System.log(y)
for each(var z in test){System.log(z)}
}
System.log(i)
}
for each (
var n in test
) {
System.log(n)
}
for (var i in test) {
System.log(i)
}
for (var $index in test) {
var i = test[$index]
System.log(i)
}
```
is converted to
```js
/**
* @return {string}
*/
(function() {
var test = ["ya", "da"]
for (var $index_i in test) {
var i = test[$index_i];
for (var $index_y in test) { …
```

[vropkg] (#365) Support for transforming `for each` statements when pulling

---

docs/versions/latest/Release.md
packages/ecmascript/src/Shims.ts

Change default return Object of `Array.from()` Method to be empty array.

[ecmascript] Change default return Object of `Array.from()` Method to be empty array

---

docs/versions/latest/Release.md
maven/archetypes/actions/src/main/resources/archetype-resources/pom.xml
maven/archetypes/mixed/src/main/resources/archetype-resources/actions/pom.xml
maven/archetypes/ts-vra-ng/src/main/resources/archetype-resources/vro/pom.xml
maven/archetypes/ts/src/main/resources/archetype-resources/pom.xml
maven/archetypes/vrealize/src/main/resources/archetype-resources/vro/actions/pom.xml
maven/base-package/pom.xml

All archetypes that generate projects with Javascript and Typescript code have exclusion rules that skip adding license headers for test files.
#379

[maven] (#379) Exclude license headers generation for javascript and typescript test files

---

docs/versions/latest/Release.md
typescript/vrotsc/src/compiler/program.ts
typescript/vrotsc/src/compiler/transformer/fileTransformers/action.ts
typescript/vrotsc/src/compiler/transformer/fileTransformers/resource.ts
typescript/vrotsc/src/compiler/transformer/helpers/checkActionForMisplacedClassDecorators.ts
typescript/vrotsc/src/compiler/transformer/helpers/checkResourceForMisplacedDecorators.ts

Replaces the non-specific error of the type "SyntaxError: [9:15]: Unexpected token: '-'" thrown when a file has an unsupported extension (e.g. .wf):
- in the cases when a .ts Action file contains a Workflow, Configuration or PolicyTemplate decorator:
- in the cases when the file extension is .pl, .wf, .conf (omitted .ts/.xml/.yaml extension):
- in the case of all other unsupported file extensions, the file is treated as Resource, retaining the existing behavior.
Tested manually on a new TS archetype project.
Closes #301

[vrotsc] (#301) Improve error messages for Policy Template, Workflow and Configuration files with incorrect extensions

---

packages/ecmascript/src/Module.ts

Removed the function Module.export.from as discussed on roadmap meeting.
The function 'from' is not part of the interface ModuleExport and is not used anywhere within the project.
Pushed to test environment without issue.
[](https://github.com/vmware/build-tools-for-vmware-aria/issues/402)
Closes #402

[ecmascript] (402) Remove unused function `Export.from` from class `Module`

---

docs/versions/latest/Release.md
packages/ecmascript/src/Module.ts

Removed "export" from a constant in Module.ts, which was causing the error.
Built successfully, tested imports on environment with the sample project.
https://github.com/vmware/build-tools-for-vmware-aria/issues/417
PR that introduced the issue:
https://github.com/vmware/build-tools-for-vmware-aria/pull/345

[ecmascript] (#417) Fix `exports` failure during TS Workflow execution

---

docs/versions/latest/Release.md
typescript/vropkg/src/parse/transformers.ts

`for each` transformers will not transform the code inside of comments
Sample PR title:
[artifact-manager] (#220) Update the package.json template for generating ABX actions
-->
TBD
TBD
Fixes: #415

[vropkg] (#415) `for each` transformer now respects comments and will not work in them

---

common/artifact-manager/pom.xml
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/configuration/Configuration.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/configuration/ConfigurationException.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/configuration/ConfigurationSsh.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/configuration/ConfigurationVraNg.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/configuration/ConfigurationVro.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/configuration/ConfigurationVrops.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClient.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientCs.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientFactory.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVraNgPrimitive.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVraPrimitive.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVro.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVroBasicAuthNInterceptor.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVrops.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVropsBasicAuthInterceptor.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgCustomResourceStore.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/helpers/vrang/RestClientVraNgPrimitiveTestDouble.java
docs/versions/latest/Release.md
maven/plugins/vrealize/src/main/java/com/vmware/pscoe/maven/plugins/PushMojo.java
maven/plugins/vrealize/src/main/java/com/vmware/pscoe/maven/plugins/package-info.java

Trivy identified critical and high level vulnerabilities in the spring framework and snakeyaml dependencies for artifact-manager.
These were resolved by using the latest versions of com.fasterxml.jackson (of which snakeyaml is a transitive dependency) and org.springframework; this required upgrading org.apache.httpcomponents to 5.3, affecting: 
- HttpClient initialization
- usage of HttpStatus
- BasicAuthorizationInterceptor (replaced by BasicAuthenticationInterceptor)
- handling of URISyntaxException and ConfigurationException
After the upgrade, no more critical or high level vulnerabilities were detected by trivy.
Builds and deploys test project successfully to environment.
https://github.com/vmware/build-tools-for-vmware-aria/issues/331

[artifact-manager] (#331) Fix CRITICAL and HIGH level vulnerabilities

---

docs/versions/latest/Release.md
packages/exec/src/main/resources/Workflow/PSCoE/Library/vRO/Exec/Run Script.xml

Changes in packages > exec > Run Script XML WF enabling the display in the OUTPUT of the Server/System logs collected in the vRealize Developer Tools plugin.
Tested with changes from related PR
https://github.com/vmware/vrealize-developer-tools/issues/159
https://github.com/vmware/vrealize-developer-tools/pull/160

[vrdt,packages] (vrdt #159) Restore System and Server logs in vRDT OUTPUT during `Run vRO Action` command

---

common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/configuration/ConfigurationVraNg.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/configuration/ConfigurationVroNg.java
common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/utils/VraNgOrganizationUtil.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgApprovalPolicyStoreTest.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgContentSharingPolicyStoreTest.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgCustomResourceStoreTest.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgDay2ActionsPolicyStoreTest.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgDeploymentLimitPolicyStoreTest.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgLeasePolicyStoreTest.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgPropertyGroupStoreTest.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgResourceQuotaPolicyStoreTest.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/store/vrang/VraNgSubscriptionStoreTest.java
docs/versions/latest/Components/Archetypes/vRA 8.x/General/Getting Started.md
docs/versions/latest/Release.md
maven/base-package/cs-package/pom.xml
maven/base-package/pom.xml
maven/base-package/serverless/pom.xml
maven/base-package/vra-ng-package/pom.xml
maven/polyglot/pom.xml
package-installer/src/main/java/com/vmware/pscoe/iac/installer/Installer.java

`vrang.org.id` has been removed in favor of `vrang.org.name`
Unit tests are green

[maven,artifact-manager,installer] (#498) Remove `vrang.org.id` and `vrang_org_id` configuration properties

---

docs/versions/latest/Release.md
package-installer/pom.xml
package-installer/src/main/java/com/vmware/pscoe/iac/installer/Installer.java

Add Support for YAML input format for the workflow inputs / outputs when workflow is ran via the installer. 
If the input / output files that is specified via the installer parameters are in YAML format it will be used as workflow input. / output. 
JSON format is still supported as well.
The testing procedure is following:
1. Create a VRO project that has at least one workflow that contains input and output parameters.
2. Push the project to an environment
3. Create package installer (-Pbundle-with-installer)
4. Create inputs.yaml and outputs.yaml files. Define the input parameters in the first file.
5. Create an environment.properties file that contains the id of the pushed workflow and paths to the files created in step 4.
6. Run the installer script.
Add Support for YAML input format …

[installer] (#467) Add Support for YAML Input Format when Running Workflows via the Installer

---

common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVro.java
common/artifact-manager/src/test/java/com/vmware/pscoe/iac/artifact/rest/vro/RestClientVroTest.java
docs/versions/latest/Release.md

When there was a disparity between the parameters provided for the vro workflow and their types, a NullPointerException was thrown. Now there is a clearer message.
Added unit tests.
Closes: #533

[artifact-manager] (#533) Better error handling when parameters are missing types

---

common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/rest/RestClientVraNgPrimitive.java
docs/versions/latest/Release.md

An exception was thrown like: `The request was rejected because the URL contained a potentially malicious String "//"","path":"/blueprint/api/blueprints/b355c354-a4b6-4d55-800a-8b4232f29b83/versions/2024-12-06-18-34-42//actions/unrelease`
This was because of the `//` after the version id.
Closes #562

[artifact-manager] (#562) Unreleasing blueprint versions fails

---

docs/versions/latest/Release.md
package-installer/src/main/java/com/vmware/pscoe/iac/installer/Installer.java

The default value was `Y` which often results in the user having to provide explicitly `N` as value.
In interactive mode, it is assumed that the Java Installer is run manually by a user. In that case if the user wants to run a workflow it is more common to login into the Aria Automation Orchestrator UI and run the workflow from there benefiting from all of the tracking and monitoring offered by Aria Automation Orchestrator.
The default value is set to `N` enabling the user to just proceed to the next option without providing explicit value for the most common use cases.
There was a `(Y/N)` hardcoded in the question which resulted in double entry:
`Is single tenant environment (Y/N)? (Y/N) [Y]:`
The question is updated:
`Is single tenant environment? (Y/N) [Y]:`
Closes #568

[installer] (#568) Default value of `Run vRO workflow?` interactive installer option changed to `N`

---

.github/workflows/build.yml
.github/workflows/release-drafter.yml
.github/workflows/release.yml
.github/workflows/trivy.yml

Closes the following security issues:
https://github.com/vmware/build-tools-for-vmware-aria/security/code-scanning/192
https://github.com/vmware/build-tools-for-vmware-aria/security/code-scanning/194
https://github.com/vmware/build-tools-for-vmware-aria/security/code-scanning/195
https://github.com/vmware/build-tools-for-vmware-aria/security/code-scanning/196
https://github.com/vmware/build-tools-for-vmware-aria/security/code-scanning/197

[github] Add commit hashes to action dependencies

---

docs/versions/latest/Release.md
typescript/vro-scripting-api/src/api/Server.ts
typescript/vro-scripting-api/src/configurations.ts
typescript/vro-scripting-api/src/resources.ts
vro-types/o11n-core/index.d.ts

Noticed that when working with `Server.getConfigurationElementCategoryWithPath` it could return `null`, while the type definition does not reflect that.
I hope I adjusted the correct files. Reading #351, I updated the definitions in `vro-scripting-api` and in `vro-types`.
The unit tests already assert the return value `.not.tobeNull()`. This PR only updates the return types of these functions.
The changes are based on the JSDoc comment mentioning "or null if not found".
But verified this in an actual vRO environment.
Tested in a live vRO tenant that the functions indeed do return `null` if not found.
Improve type definitions of Server class functions by adding `| null` to the return type.

[vro-scripting-api,vro-types] Add optional null output for `Server` class functions

---

docs/versions/latest/Release.md
typescript/vrotsc/src/compiler/transformer/fileTransformers/workflow/decorators/decisionItemDecoratorStrategy.ts

Confirmed issue on v3.2.0. Tested fix by building a project inWF containing DecisionItem with closing brackets in its contents.
Closes #615

[vrotsc] (#615) Fix incorrectly transpiled `DecisionItem` Workflow decorator

---

maven/plugins/common/pom.xml
maven/plugins/common/src/main/java/com/vmware/pscoe/maven/plugins/AbstractVroTestMojo.java
maven/plugins/typescript/pom.xml
maven/plugins/typescript/src/main/java/com/vmware/pscoe/maven/plugins/TypescriptTestMojo.java

[vrotsc, maven] Update Javadoc. 
Updated java doc and removed dependency to the javadoc plugin in the maven/plugins/common and vrotsc modules.
Run build of those components locally using
```bash
mvn clean install
```
Updated java doc and removed dependency to the javadoc plugin in the maven/plugins/common and vrotsc modules.

[maven/plugins] Update Javadoc

---

common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/aria/automation/rest/RestClientVraNgPrimitive.java
docs/versions/latest/Release.md

CSPs could not be imported due to a forgotten fetch before creation.
When importing we were getting an error that id is expected of type UUID.String but was null
CSPs are no longer fetched prior to updating to set their ID.

[artifact-manager] Remove fetching of Content Sharing Policies before creation

---

docs/versions/latest/Release.md
package-installer/etc/logback.xml
package-installer/pom.xml
package-installer/src/assembly/package-installer.xml

[installer] Add Logging Configuration for the Installer
Added logging configuration file *etc/logback.xml* in the installer bundle where the logging severity can be configured during running installer (or installer.bat). By default the logging severity is set to *INFO* and *WARN*, You can set it to *DEBUG* if further tracing is needed.
1. Create a mixed archetype project.
2. Go to the project and execute
```bash
mvn clean package -Pbundle-with-installer
```
3. Go to the project's target directory and invoke
```bash
unzip <project_name>-bundle.zip
```
4. Go to the unzipped directory and run
(on Linux )
```bash
installer environment.properties
```
(on Windows) 
```bash
installer.bat environment.properties
```
Note: You need to create the *environment.properties* file separately where the …

[installer] (#658) Add Logging Configuration for the Installer

---

.github/linters/sun_checks.xml
docs/versions/latest/Release.md
maven/plugins/common/src/main/java/com/vmware/pscoe/maven/plugins/AbstractVroTestMojo.java
typescript/vrotest/src/run.ts

TESTING fixes for "Error occurred in unit tests execution:" shown on Linux and Mac when building (with) BTVA v4.3.0+
Tested by building BTVA in Github and having the results verified on Mac
https://github.com/vmware/build-tools-for-vmware-aria/issues/691

[vrotest] (#691) Error running unit tests on Mac/Linux

---

README.md
docs/versions/latest/Release.md

[docs] Add `go-btva` link to quickstart guide for easy BTVA setup

---

docs/versions/latest/Release.md
typescript/vro-scripting-api/src/api/ConfigurationElement.ts
typescript/vro-scripting-api/src/api/Workflow.ts
typescript/vro-scripting-api/src/api/WorkflowToken.ts
vro-types/o11n-core/index.d.ts

Similar as #627. Noticed some inaccurate type definitions with the following items:
- `ConfigurationElement.getAttributeWithKey` function might return `null`. Implementation can be seen here: https://github.com/vmware/build-tools-for-vmware-aria/blob/main/typescript/vro-scripting-api/src/api/ConfigurationElement.ts#L40 ![Pasted image 20250512143307](https://github.com/user-attachments/assets/6d036d8c-2fad-4dd8-aa5f-71302f13b6e5)
- `Properties`
- `.get()` add optional null output to type definition. Possible value can be seen in the implementation here: https://github.com/vmware/build-tools-for-vmware-aria/blob/main/typescript/vro-scripting-api/src/api/Properties.ts#L33
- `.remove()` change return type from `any` to `void`. It doesn't return a value, as can be seen in the implementation …

[vro-scripting-api,vro-types] Improve type definitions of `ConfigurationElement`, `Properties`, and `Workflow` properties/functions
